### PR TITLE
Apply workaround for issue #15 since Progress changed something in Op…

### PR DESCRIPTION
**Pull request by LievenDeFoor**
…enEdge 11.5/11.6 causing error 2780 when trying to run a test.

### CODE REVIEW

**Comment by LievenDeFoor** [comment]
Hi Cameron,

I've applied a workaround for issue #15 by replacing the property by a VOID method.
OpenEdge currently can't have WAIT-FORs when there are non-void methods (a property getter is in fact a non-void method) in the stack. I've also changed the DisplayRunning and DisplayError return types to void for the same reason. Luckily they didn't return anything in the first place, so no other changes needed to be made.

Can you merge this into master?

Thanks,
Lieven

**Comment by msabbott** [comment]
Hi Lieven,

Thanks for submitting the Pull Request - have you been able to test it in earlier versions of OE? If not, I can test it on 11.4.

I'll have a look through the code and pull it through if appropriate.

Thanks,
Mark

**Comment by LievenDeFoor** [comment]
Hi Mark,

No I haven't tested it in 11.4 (or even 11.5 for that matter), only 11.6

The change is version independent though and I don't expect any issues with
earlier versions (11.3 and below should not have any problem with this
change either).

You'll see the changes are quite trivial, and are merely meant to
circumvent the use of non-void methods when a WAIT-FOR could occur.

Kind regards,
Lieven

2015-11-30 13:34 GMT+01:00 Mark Abbott <notifications@github.com>:

**Comment by msabbott** [comment]
Thanks Lieven.

I've tested on OE 11.4 and can't see any issues. The existing unit tests still pass. I'll approve the PR.

Mark

**Pull request merged**
